### ISSUE TITLE
Unable to use directory in WIN Edge and please support hotkeys

### ISSUE THREAD

**Issue by gesen2egee** [QuentinWach/image-ranker#1]
![image](https://github.com/user-attachments/assets/10244cce-3f7c-4d9d-bd9c-46abd613e7b0)

Unable to use directory in WIN Edge
Please support keyboard hotkeys; 
even just 1 and 2 would be very useful

Thank you for your work.

**Comment by QuentinWach** [comment]
**Thank you** for trying out Image Rankger and thank you for the helpful feedback and suggestion!

I wasn't able to reproduce the WIN Edge error. I believe the issue may be with the directory or the files contained in it.
However, I have added the hotkey functionality. You can now use the 1 and 2 keys or the left and right arrow keys to press the main buttons.
