### ISSUE TITLE
Feature request: Option to eliminate images from the ranking process for even faster results.

### ISSUE THREAD

**Issue by QuentinWach** [QuentinWach/image-ranker#2]
In order to speed up the ranking process, add the optional feature to eliminate images (they won't be shown for comparison again) after being downvoted. Importantly, their ranking ELO should continue being updated and they should still be shown in the ranking list.

**Comment by diensii** [comment]
Just to preface as a disclaimer, I have basically no idea how to use Git and barely know what I'm doing.

I made a branch of your repo where I basically did this and some other minor changes however for my use case I wanted to exclude the removed image entirely from the rankings. 

```
@app.route('/remove_image', methods=['POST'])
def remove_image():
    image = request.json['del_img']
    image = image.replace('/', '\\')
    image = image.replace('\\serve_image?path=', '')
    image = image.replace('static\\', 'static/')

    global image_pairs
    image_pairs = [(img1, img2) for img1, img2 in image_pairs if img1!= image and img2!= image]
    elo_ranking.remove_image(image)

    return jsonify({'success': True})
```
	
This bit (without the elo_ranking.remove_image(image)) bit and the corresponding button in the html should do what you want.

**Comment by QuentinWach** [comment]
First of all, **thank you** for giving Image Ranker a shot, even going so far to modify it your needs. And thank you for your help!
I've looked into your repo and I think you added some pretty useful features. You did a lot. Awesome 👍.
Please don't shy away to send me a _pull request_ to add new features or just suggest new features here in the _Issues_.
In any case, I'll think about how to integrate your contribution within the next 24 hrs.

**Comment by QuentinWach** [comment]
I just realized that I implemented this feature, so I am closing this issue.
