### ISSUE TITLE
Documentation Request for New Buttons

### ISSUE THREAD

**Issue by IndigoDosSantos** [QuentinWach/image-ranker#8]
First of all, this is an absolutely great app and I love the clean, minimalistic GUI. Thank you!

I've noticed there are some new buttons, and I'm unsure of what their use cases are. I'd appreciate some documentation for the cyan-colored ones. Would you mind adding it to the README file?

Anyway, thanks again for this super app! 💯

![new_buttons](https://github.com/user-attachments/assets/2a0987ba-adbd-4c66-a90f-5fdb4e2da5c5)

**Comment by QuentinWach** [comment]
**Thank you!** The positive feedback means a lot to me. And your critique and questions as well!

I spent a lot of time adding a feature that explains what these buttons do when you hover on top of them like so
![image](https://github.com/user-attachments/assets/788a1328-bd18-43b7-8ad6-9e2f4e7e711d)
so I sure hope that it is visible! If not, please do tell me so I may fix it. 

I think the two buttons here are not well integrated into the app and its algorithm yet. Personally, I haven't found much use for them even though, in theory, they should be quite helpful. So I think you are also right that it is probably time to start adding more detailed documentation for these buttons especially to at least clear up what their purpose is. I am on it :)

Let me give you a quick answer right now:

**LEFT BUTTON (Smart Shuffle)**
Clicking this button reorders the list of image pairs to prioritize comparisons between images with similar ratings and fewer previous comparisons. This is meant to decrease uncertainty and further differentiate the images in their ranking faster.

**RIGHT BUTTON (Auto Shuffle)**
Activating this toggle button simply smart shuffles the images every three comparisons so you don't have to do it manually.

**Comment by QuentinWach** [comment]
I hope my answer and the added documentation is sufficient for now. Thanks again for the feedback!
